version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    hostname: keycloak
    ports: 
      - 8080:8080
    environment:
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      #- KEYCLOAK_ADMIN=admin
      #- KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/import/realm-export.json
    volumes: 
      - ./keycloak:/tmp/import
    networks:
      #- nef_emulator_default
      - testnet

  IQB_netapp:
    image: iqb_netapp_img
    container_name: iqb_netapp
    hostname: iqb_netapp
    #list of environment variables
    environment:
      NETAPP_ID: "${netapp_id}"
      NETAPP_NAME: "${netapp_name}"
      NETAPP_IP: "${netapp_ip}"
      NETAPP_SERVER_VAPP: "${netapp_server_vapp}"
      NETAPP_PORT_5G: "${netapp_port_5g}"
      NETAPP_PORT_WEB: "${netapp_port_web}"
      NETAPP_PORT_VAPP: "${netapp_port_vapp}"
      NEF_CALLBACK_URL: "${nef_callback_url}"
      NEF_HOST: "${nef_host}"
    build:
    #path to src code
      context: ./
    ports:
      - 5000:5000
    # network bridge with nef_emulator_default to be able to reach the NEF emulator 
    networks:
      #- nef_emulator_default
      - testnet

#volumes:
#  keycloak:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: /tmp/keycloak/config
      
networks:
  testnet:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
  #nef_emulator_default:
  #  external: true
