version: '3'

services:
  keycloak:
    image: keycloak_img #quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    hostname: keycloak
    ports: 
      - 8980:8080
    environment:
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      #- KEYCLOAK_ADMIN=admin
      #- KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/import/realm-export.json
    #volumes: 
    #  - ./keycloak:/tmp/import
    build:
      context: ./keycloak
    networks:
      #- nef_emulator_default
      - services_default

  IQB_netapp:
    image: iqb_netapp_img
    container_name: iqb_netapp
    hostname: iqb_netapp
    #list of environment variables
    environment:
      NETAPP_ID: "myNetapp"
      NETAPP_NAME: "${netapp_name}"
      NETAPP_IP: "${netapp_ip}"
      NETAPP_SERVER_VAPP: "${netapp_server_vapp}"
      NETAPP_PORT_5G: "${netapp_port_5g}"
      NETAPP_PORT_WEB: "${netapp_port_web}"
      NETAPP_PORT_VAPP: "${netapp_port_vapp}"
      NEF_CALLBACK_URL: "${nef_callback_url}"
      KEYCLOAK_ADDRESS: "keycloak:8080/auth"
      KEYCLOAK_REALM: "EVOLVED-5G"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      NEF_ADDRESS: "nef_emulator_backend_1:80"
      NEF_USER: "admin@my-email.com"
      NEF_PASSWORD: "pass"
      VAPP_ADDRESS: "NA"
      PATH_TO_CERTS: "/app/capif_onboarding"
      CAPIF_HOSTNAME: "capifcore"
      CAPIF_PORT_HTTP: "8080"
      CAPIF_PORT_HTTPS: "443"
      CALLBACK_ADDRESS: "callbacks:5002"
      FRONTEND_ADDRESS: "NA"
    build:
    #path to src code
      context: ./
    depends_on:
      - keycloak
    ports:
      - 5000:5000
    # network bridge with nef_emulator_default to be able to reach the NEF emulator 
    networks:
      #- nef_emulator_default
      - services_default

  callbacks:
    image: callbacks
    container_name: callbacks
    hostname: callbacks
    build:
    #path to src code
      context: ./callbacks
    ports:
      - 5002:5002
    # network bridge with nef_emulator_default to be able to reach the NEF emulator 
    networks:
      #- nef_emulator_default
      - services_default 

#volumes:
#  keycloak:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: /tmp/keycloak/config
      
networks:
  services_default:
    #external: true
  #nef_emulator_default:
  #  external: true
